name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake -B_build
      - name: Build project
        run: |
          cmake --build _build --config Release
          dir
          tree _build
          mkdir artifacts
          copy _build/Release/Cpp-Software-Design.exe artifacts
          mv _build artifacts
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts
  test:
runs-on: ubuntu-latest
